### PR TITLE
Silence warnings preventing to compile with g++ 6.2.0 Fix #9

### LINKED ISSUE #9: doesn't compile with gcc6/g++6
There are warnings with g++6 compiler on Linux and as -Werror is activated, it doesn't compile. 

I had to add both `-Wno-misleading-indentation` and `-Wno-strict-aliasing`  in order to silence those warnings and successfully compile.

### PR DESCRIPTION
**Pull request by Sumenia**

### CODE REVIEW

**Comment by Sumenia** [comment]
The problem is :
```
[ 62%] Building CXX object CMakeFiles/Anvil.dir/src/misc/page_tracker.cpp.o
/home/sumenia/Anvil/src/misc/object_tracker.cpp: In member function ‘void Anvil::ObjectTracker::check_for_leaks() const’:
/home/sumenia/Anvil/src/misc/object_tracker.cpp:66:21: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
             ++(int&)current_object_type)
                     ^~~~~~~~~~~~~~~~~~~

``` 

As i understand, this is happening because there is a type-punning of the enum by casting it to an int and this may lead to undefined behavior:
```
    for (ObjectType current_object_type = OBJECT_TYPE_FIRST;
                    current_object_type < OBJECT_TYPE_COUNT;
            ++(int&)current_object_type)

```
As i far as i know, there is two way to solve this in C++
Either by doing this, and this is perfect because you do have OBJECT_TYPE_COUNT defined as the last element of the enum 
```
    for (int current_object_type_it = OBJECT_TYPE_FIRST;
                    current_object_type_it < OBJECT_TYPE_COUNT;
         ++current_object_type_it)
      {
        ObjectType current_object_type = static_cast<ObjectType>(current_object_type_it);
``` 
Or we could overload the ++ and -- on the enum type.

**Comment by janisozaur** [comment]
The fix is easy, but doesn't look as nice:
```
current_object_type = (ObjectType)(current_object_type + 1)
```

**Comment by janisozaur** [comment]
All things are fixed in https://github.com/GPUOpen-LibrariesAndSDKs/Anvil/pull/17, there won't be need to disable warnings anymore.
